<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFQoSX4G\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFQoSX4G/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFQoSX4G.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFQoSX4G\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFQoSX4G\App_KernelDevDebugContainer([
    'container.build_hash' => 'FQoSX4G',
    'container.build_id' => '2e28b9d6',
    'container.build_time' => 1762594754,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFQoSX4G');
