<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHpLAUMl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHpLAUMl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHpLAUMl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHpLAUMl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHpLAUMl\App_KernelDevDebugContainer([
    'container.build_hash' => 'HpLAUMl',
    'container.build_id' => 'b5b5f8d2',
    'container.build_time' => 1762595612,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHpLAUMl');
